### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by Eversor** [redblobgames/dual-mesh#4]
Dear RedBlobGames, i was wondering if you could add a MIT license to this code so that we can legally use it?

**Comment by Eversor** [comment]
If this is not your intention i'm sorry for being supponent.

**Comment by redblobgames** [comment]
Hi Eversor, the code is under the Apache v2 license so you can use it. I will add the license to the github page. Thanks!

I'm still working on the interface, so some of the functions will probably change as I update my map project. You may want to fork it if you don't want to worry about the changes.
